#!/usr/bin/env ruby
require 'date'
require 'git-blog/configuration'

$msg_path = ARGV[0]
content = File.read($msg_path)

conf = GitBlog::Configuration.new
conf.read

# Create a new blog file
time = DateTime.now.strftime("%F")
title = [time, "blogging-with-git-blog"].join("-")
path = File.join conf.blog_path, title

File.open(path, "w") do |file|
	file.write content
end